compute_environment: LOCAL_MACHINE
deepspeed_config: {}
distributed_type: MULTI_GPU
fsdp_config: {}
machine_rank: 0
main_process_ip: 127.0.0.1
main_process_port: 85400
main_training_function: main
mixed_precision: fp16
num_machines: 1
num_processes: 4
use_cpu: false
